### ISSUE TITLE
Suggestion: Pre built uf2 file

### ISSUE THREAD

**Issue by podpah** [untoxa/pico-gb-printer#15]
Hey, I'm making this suggestion because I think it would be more convenient for people who want to use this to have access to the uf2 file either in the releases part of the repo, or possibly in the code (maybe a branch with just the .uf2?). 

If you like the idea and would prefer the branch option I'm happy to rebuild and make a PR. If you like it and think a release would be cleaner, I can't do that myself due to perms but I'm guessing already have it built (or at least the SDK installed) so shouldn't be too time consuming to add it as a release?

**Comment by untoxa** [comment]
There is an uf2 file in the build folder of the repo.

**Comment by podpah** [comment]
Ah, my bad. Didn't see anything on the readme about it so didn't even take a look, sorry.
