### ISSUE TITLE
Black is not black

### ISSUE THREAD

**Issue by Windestal** [untoxa/pico-gb-printer#16]
Hi guys!
When I download gameboy camera images blacks come out as dark gray instead of completely black. It's pretty easy to see on the border.
![image_08-09-2024_17-19-15_360](https://github.com/user-attachments/assets/dae63b15-850e-4d7d-bcd7-a768a353a6a7)
Not sure if the white is 100% white either.
Am I doing something wrong?
Thanks for the excellent project!

Edit: What does the "Tear" function do?

**Comment by untoxa** [comment]
device respect the darkness settings which ROM pass to the printer when printing. you get dark gray if the ROM tells printer that.

device keep printed images in memory (up to 30 images). when you press "get images", you receive all images from memory. if you press twice, then you get the same images twice. "tear" button clears the device memory, similar to the real game boy printer, where you tear the pictures off the paper roll, device memory is that "roll".
